# -*- coding: utf-8 -*-
"""python_sql .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6Sipjk-yQhjuiHbbPKDHpQ1Ty0B68E6
"""

from google.colab import files
uploaded = files.upload()

!python generate_data.py

!python clean_data.py

!python load_to_db.py

!python queries.py

!python report_cli.py

!python test_edge_cases.py

!python report_cli.py --type monthly --start 2025-01-01 --end 2025-02-01

import sqlite3, pandas as pd
conn = sqlite3.connect("ecommerce.db")
pd.read_sql_query("SELECT * FROM orders LIMIT 5", conn)

from google.colab import files
files.download("ecommerce.db")

import sqlite3
import pandas as pd

conn = sqlite3.connect("ecommerce.db")

q1 = """
SELECT
    p.category,
    ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent/100.0)), 2) AS total_revenue
FROM order_items oi
JOIN products p ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;
"""
pd.read_sql_query(q1, conn)

q2 = """
SELECT
    o.customer_id,
    ROUND(SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent/100.0)), 2) AS total_order_value
FROM order_items oi
JOIN orders o ON o.order_id = oi.order_id
WHERE o.customer_id IS NOT NULL AND o.customer_id != ''
GROUP BY o.customer_id
ORDER BY total_order_value DESC
LIMIT 10;
"""
pd.read_sql_query(q2, conn)

q3 = """
SELECT
    strftime('%Y-%m', order_date) AS year_month,
    COUNT(*) AS order_count
FROM orders
WHERE order_date >= date((SELECT MAX(order_date) FROM orders), '-12 months')
GROUP BY year_month
ORDER BY year_month;
"""
pd.read_sql_query(q3, conn)

q4 = """
SELECT DISTINCT o.customer_id
FROM orders o
WHERE o.customer_id IS NOT NULL AND o.customer_id != ''
  AND o.customer_id NOT IN (
      SELECT customer_id FROM orders
      WHERE status = 'DELIVERED' AND customer_id IS NOT NULL AND customer_id != ''
  );
"""
pd.read_sql_query(q4, conn)

q5 = """
SELECT
    p.product_id,
    p.product_name,
    SUM(CASE WHEN oi.quantity > 0 THEN oi.quantity ELSE 0 END) AS purchased_qty,
    SUM(CASE WHEN oi.quantity < 0 THEN -oi.quantity ELSE 0 END) AS returned_qty
FROM order_items oi
JOIN products p ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
HAVING returned_qty > purchased_qty
ORDER BY returned_qty DESC;
"""
pd.read_sql_query(q5, conn)

q6 = """
SELECT
    p.category,
    SUM(CASE WHEN oi.quantity < 0 THEN -oi.quantity ELSE 0 END) AS returned_items,
    SUM(ABS(oi.quantity)) AS total_items,
    ROUND(
        1.0 * SUM(CASE WHEN oi.quantity < 0 THEN -oi.quantity ELSE 0 END)
        / NULLIF(SUM(ABS(oi.quantity)), 0), 4
    ) AS return_rate
FROM order_items oi
JOIN products p ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY return_rate DESC;
"""
pd.read_sql_query(q6, conn)

q7 = """
WITH daily AS (
    SELECT
        o.region_code,
        date(o.order_date) AS order_date,
        SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent/100.0)) AS daily_revenue
    FROM order_items oi
    JOIN orders o ON o.order_id = oi.order_id
    GROUP BY o.region_code, date(o.order_date)
)
SELECT
    region_code,
    order_date,
    ROUND(daily_revenue, 2) AS daily_revenue,
    ROUND(SUM(daily_revenue) OVER (
        PARTITION BY region_code ORDER BY order_date
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ), 2) AS running_total
FROM daily
ORDER BY region_code, order_date;
"""
pd.read_sql_query(q7, conn)

q8 = """
WITH product_revenue AS (
    SELECT
        p.category,
        p.product_name,
        SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent/100.0)) AS total_revenue
    FROM order_items oi
    JOIN products p ON p.product_id = oi.product_id
    GROUP BY p.category, p.product_name
)
SELECT
    category,
    product_name,
    ROUND(total_revenue, 2) AS total_revenue,
    DENSE_RANK() OVER (PARTITION BY category ORDER BY total_revenue DESC) AS rank_in_category
FROM product_revenue
ORDER BY category, rank_in_category;
"""
pd.read_sql_query(q8, conn)

q9 = """
WITH customer_orders AS (
    SELECT customer_id, order_date
    FROM orders
    WHERE customer_id IS NOT NULL AND customer_id != ''
),
gaps AS (
    SELECT
        customer_id,
        order_date,
        LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS previous_order_date,
        julianday(order_date) - julianday(
            LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date)
        ) AS days_gap
    FROM customer_orders
)
SELECT
    customer_id,
    order_date,
    previous_order_date,
    ROUND(days_gap, 1) AS days_gap,
    CASE WHEN avg_gap > 30 THEN 'At Risk' ELSE 'Active' END AS risk_flag
FROM gaps
JOIN (
    SELECT customer_id, AVG(days_gap) AS avg_gap
    FROM gaps
    WHERE days_gap IS NOT NULL
    GROUP BY customer_id
) avgs USING (customer_id)
ORDER BY customer_id, order_date;
"""
pd.read_sql_query(q9, conn)

q10 = """
WITH monthly_customer_revenue AS (
    SELECT
        o.customer_id,
        strftime('%Y-%m', o.order_date) AS year_month,
        SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent/100.0)) AS revenue
    FROM order_items oi
    JOIN orders o ON o.order_id = oi.order_id
    WHERE o.customer_id IS NOT NULL AND o.customer_id != ''
    GROUP BY o.customer_id, year_month
),
tiered AS (
    SELECT
        customer_id,
        year_month,
        revenue,
        CASE
            WHEN revenue > 10000 THEN 'High'
            WHEN revenue >= 5000 THEN 'Medium'
            ELSE 'Low'
        END AS tier
    FROM monthly_customer_revenue
)
SELECT
    year_month,
    tier,
    COUNT(*) AS customer_count
FROM tiered
GROUP BY year_month, tier
ORDER BY year_month, tier;
"""
pd.read_sql_query(q10, conn)

q11 = """
WITH customer_ltv AS (
    SELECT
        o.customer_id,
        SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent/100.0)) AS total_value
    FROM order_items oi
    JOIN orders o ON o.order_id = oi.order_id
    WHERE o.customer_id IS NOT NULL AND o.customer_id != ''
    GROUP BY o.customer_id
)
SELECT
    customer_id,
    ROUND(total_value, 2) AS total_value,
    NTILE(4) OVER (ORDER BY total_value DESC) AS quartile,
    CASE NTILE(4) OVER (ORDER BY total_value DESC)
        WHEN 1 THEN 'Platinum'
        WHEN 2 THEN 'Gold'
        WHEN 3 THEN 'Silver'
        WHEN 4 THEN 'Bronze'
    END AS quartile_label
FROM customer_ltv
ORDER BY total_value DESC;
"""
pd.read_sql_query(q11, conn)

q12 = """
WITH monthly_revenue AS (
    SELECT
        CAST(strftime('%Y', o.order_date) AS INTEGER) AS year,
        CAST(strftime('%m', o.order_date) AS INTEGER) AS month,
        SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent/100.0)) AS revenue
    FROM order_items oi
    JOIN orders o ON o.order_id = oi.order_id
    GROUP BY year, month
)
SELECT
    cur.year,
    cur.month,
    ROUND(cur.revenue, 2) AS revenue,
    ROUND(prev.revenue, 2) AS prev_year_revenue,
    CASE
        WHEN prev.revenue IS NULL OR prev.revenue = 0 THEN NULL
        ELSE ROUND(100.0 * (cur.revenue - prev.revenue) / prev.revenue, 2)
    END AS yoy_growth_percent
FROM monthly_revenue cur
LEFT JOIN monthly_revenue prev
    ON prev.year = cur.year - 1 AND prev.month = cur.month
ORDER BY cur.year, cur.month;
"""
pd.read_sql_query(q12, conn)

q13 = """
WITH customer_category_orders AS (
    SELECT
        o.customer_id,
        p.category,
        o.order_date,
        ROW_NUMBER() OVER (PARTITION BY o.customer_id ORDER BY o.order_date ASC) AS rn_first,
        ROW_NUMBER() OVER (PARTITION BY o.customer_id ORDER BY o.order_date DESC) AS rn_last
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    JOIN products p ON p.product_id = oi.product_id
    WHERE o.customer_id IS NOT NULL AND o.customer_id != ''
)
SELECT
    f.customer_id,
    f.category AS first_category,
    l.category AS last_category,
    CASE WHEN f.category != l.category THEN 'Yes' ELSE 'No' END AS category_shift
FROM (SELECT * FROM customer_category_orders WHERE rn_first = 1) f
JOIN (SELECT * FROM customer_category_orders WHERE rn_last = 1) l
    ON f.customer_id = l.customer_id
ORDER BY f.customer_id;
"""
pd.read_sql_query(q13, conn)

q14 = """
WITH customer_revenue AS (
    SELECT
        o.customer_id,
        SUM(oi.quantity * oi.unit_price * (1 - oi.discount_percent/100.0)) AS revenue
    FROM order_items oi
    JOIN orders o ON o.order_id = oi.order_id
    WHERE o.customer_id IS NOT NULL AND o.customer_id != ''
    GROUP BY o.customer_id
),
ranked AS (
    SELECT
        customer_id,
        revenue,
        SUM(revenue) OVER (ORDER BY revenue DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_revenue,
        SUM(revenue) OVER () AS total_revenue
    FROM customer_revenue
)
SELECT
    customer_id,
    ROUND(revenue, 2) AS revenue,
    ROUND(cumulative_revenue, 2) AS cumulative_revenue,
    ROUND(100.0 * cumulative_revenue / total_revenue, 2) AS cumulative_percent
FROM ranked
ORDER BY revenue DESC;
"""
pd.read_sql_query(q14, conn)

q15 = """
WITH cohorts AS (
    SELECT
        customer_id,
        strftime('%Y-%m', registration_date) AS cohort_month
    FROM customers
),
customer_order_months AS (
    SELECT
        o.customer_id,
        c.cohort_month,
        (
            (CAST(strftime('%Y', o.order_date) AS INTEGER) - CAST(strftime('%Y', c.cohort_month || '-01') AS INTEGER)) * 12
            + (CAST(strftime('%m', o.order_date) AS INTEGER) - CAST(strftime('%m', c.cohort_month || '-01') AS INTEGER))
        ) AS month_offset
    FROM orders o
    JOIN cohorts c ON c.customer_id = o.customer_id
    WHERE o.customer_id IS NOT NULL AND o.customer_id != ''
),
cohort_sizes AS (
    SELECT cohort_month, COUNT(DISTINCT customer_id) AS cohort_size
    FROM cohorts
    GROUP BY cohort_month
)
SELECT
    com.cohort_month,
    com.month_offset,
    COUNT(DISTINCT com.customer_id) AS active_customers,
    cs.cohort_size,
    ROUND(100.0 * COUNT(DISTINCT com.customer_id) / cs.cohort_size, 2) AS retention_rate
FROM customer_order_months com
JOIN cohort_sizes cs ON cs.cohort_month = com.cohort_month
WHERE com.month_offset BETWEEN 0 AND 3
GROUP BY com.cohort_month, com.month_offset
ORDER BY com.cohort_month, com.month_offset;
"""
pd.read_sql_query(q15, conn)

q16 = """
SELECT
    pa.product_name AS product_a,
    pb.product_name AS product_b,
    COUNT(*) AS times_bought_together
FROM order_items a
JOIN order_items b
    ON a.order_id = b.order_id
    AND a.product_id < b.product_id
JOIN products pa ON pa.product_id = a.product_id
JOIN products pb ON pb.product_id = b.product_id
GROUP BY pa.product_name, pb.product_name
ORDER BY times_bought_together DESC
LIMIT 20;
"""
pd.read_sql_query(q16, conn)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile report_cli.py
# """
# Part 4: Python + SQL Integration
# A command-line tool that generates a summary report for a date range.
# Uses ONLY the sqlite3 standard library module (no pandas), as required.
# """
# 
# import sqlite3
# import argparse
# from datetime import datetime, timedelta
# 
# DB_PATH = "ecommerce.db"
# 
# REVENUE_EXPR = "oi.quantity * oi.unit_price * (1 - oi.discount_percent/100.0)"
# 
# 
# def get_period_summary(conn, start_date, end_date):
#     """Return dict with total_orders, revenue, unique_customers, top_3_products
#     for orders with order_date in [start_date, end_date)."""
#     cur = conn.cursor()
# 
#     cur.execute(f"""
#         SELECT
#             COUNT(DISTINCT o.order_id) AS total_orders,
#             COALESCE(SUM({REVENUE_EXPR}), 0) AS revenue,
#             COUNT(DISTINCT o.customer_id) AS unique_customers
#         FROM orders o
#         LEFT JOIN order_items oi ON oi.order_id = o.order_id
#         WHERE o.order_date >= ? AND o.order_date < ?
#     """, (start_date, end_date))
#     total_orders, revenue, unique_customers = cur.fetchone()
# 
#     cur.execute(f"""
#         SELECT p.product_name, SUM({REVENUE_EXPR}) AS product_revenue
#         FROM order_items oi
#         JOIN orders o ON o.order_id = oi.order_id
#         JOIN products p ON p.product_id = oi.product_id
#         WHERE o.order_date >= ? AND o.order_date < ?
#         GROUP BY p.product_name
#         ORDER BY product_revenue DESC
#         LIMIT 3
#     """, (start_date, end_date))
#     top_products = cur.fetchall()
# 
#     return {
#         "total_orders": total_orders or 0,
#         "revenue": revenue or 0.0,
#         "unique_customers": unique_customers or 0,
#         "top_products": top_products,
#     }
# 
# 
# def previous_period(start_date, end_date):
#     """Given [start, end), return the immediately preceding period of equal length."""
#     fmt = "%Y-%m-%d"
#     start = datetime.strptime(start_date, fmt)
#     end = datetime.strptime(end_date, fmt)
#     length = end - start
#     prev_end = start
#     prev_start = start - length
#     return prev_start.strftime(fmt), prev_end.strftime(fmt)
# 
# 
# def pct_change(current, previous):
#     if previous in (0, None):
#         return None
#     return round(100.0 * (current - previous) / previous, 2)
# 
# 
# def date_range_for_report_type(report_type, anchor_date=None):
#     """Compute a default [start, end) window for daily/weekly/monthly, ending at anchor_date."""
#     fmt = "%Y-%m-%d"
#     end = datetime.strptime(anchor_date, fmt) if anchor_date else datetime.today()
#     if report_type == "daily":
#         start = end - timedelta(days=1)
#     elif report_type == "weekly":
#         start = end - timedelta(days=7)
#     elif report_type == "monthly":
#         start = end - timedelta(days=30)
#     else:
#         raise ValueError("report_type must be daily, weekly, or monthly")
#     return start.strftime(fmt), end.strftime(fmt)
# 
# 
# def print_report(report_type, start_date, end_date, conn):
#     current = get_period_summary(conn, start_date, end_date)
#     prev_start, prev_end = previous_period(start_date, end_date)
#     previous = get_period_summary(conn, prev_start, prev_end)
# 
#     print("\n" + "=" * 50)
#     print(f"{report_type.upper()} REPORT: {start_date} to {end_date}")
#     print("=" * 50)
#     print(f"Total Orders:      {current['total_orders']}"
#           f"  ({pct_change(current['total_orders'], previous['total_orders'])}% vs previous period)")
#     print(f"Revenue:           {current['revenue']:.2f}"
#           f"  ({pct_change(current['revenue'], previous['revenue'])}% vs previous period)")
#     print(f"Unique Customers:  {current['unique_customers']}"
#           f"  ({pct_change(current['unique_customers'], previous['unique_customers'])}% vs previous period)")
#     print("\nTop 3 Products:")
#     if current["top_products"]:
#         for name, rev in current["top_products"]:
#             print(f"  - {name}: {rev:.2f}")
#     else:
#         print("  (no sales in this period)")
#     print(f"\nPrevious period: {prev_start} to {prev_end}")
#     print("=" * 50)
# 
# 
# def main():
#     parser = argparse.ArgumentParser(description="E-commerce summary report generator")
#     parser.add_argument("--type", choices=["daily", "weekly", "monthly"], help="Report type")
#     parser.add_argument("--start", help="Start date YYYY-MM-DD")
#     parser.add_argument("--end", help="End date YYYY-MM-DD")
#     parser.add_argument("--db", default=DB_PATH, help="Path to SQLite database")
#     args = parser.parse_args()
# 
#     report_type = args.type
#     start_date = args.start
#     end_date = args.end
# 
#     # fall back to interactive prompts if not supplied on the command line
#     if report_type is None:
#         report_type = input("Report type (daily/weekly/monthly): ").strip().lower()
#         while report_type not in ("daily", "weekly", "monthly"):
#             report_type = input("Please enter daily, weekly, or monthly: ").strip().lower()
# 
#     if start_date is None or end_date is None:
#         use_custom = input("Enter custom date range? (y/n): ").strip().lower()
#         if use_custom == "y":
#             start_date = input("Start date (YYYY-MM-DD): ").strip()
#             end_date = input("End date (YYYY-MM-DD): ").strip()
#         else:
#             start_date, end_date = date_range_for_report_type(report_type)
# 
#     conn = sqlite3.connect(args.db)
#     try:
#         print_report(report_type, start_date, end_date, conn)
#     finally:
#         conn.close()
# 
# 
# if __name__ == "__main__":
#     main()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test_edge_cases.py
# 
# 
# from datetime import datetime, timedelta
# import pandas as pd
# 
# from clean_data import check_referential_integrity
# 
# 
# def test_order_item_with_missing_order():
#     """order_items row pointing at a non-existent order_id should be flagged
#     by check_referential_integrity, not silently dropped or crash the pipeline."""
#     orders = pd.DataFrame({
#         "order_id": [1, 2, 3],
#         "customer_id": [10, 11, 12],
#     })
#     order_items = pd.DataFrame({
#         "item_id": [100, 101],
#         "order_id": [1, 999],
#         "product_id": [5, 6],
#         "quantity": [2, 1],
#         "unit_price": [10.0, 20.0],
#         "discount_percent": [0, 0],
#     })
# 
#     bad_rows = check_referential_integrity(order_items, orders)
# 
#     assert len(bad_rows) == 1, f"expected 1 orphaned row, got {len(bad_rows)}"
#     assert bad_rows.iloc[0]["order_id"] == 999
#     print("PASS: test_order_item_with_missing_order")
# 
# 
# def test_discount_percent_over_100():
#     """discount_percent > 100 is invalid input (would produce negative revenue).
#     We verify it's detectable so the pipeline can flag/reject it rather than
#     silently generating nonsense revenue numbers."""
#     order_items = pd.DataFrame({
#         "item_id": [1, 2],
#         "order_id": [1, 1],
#         "product_id": [1, 2],
#         "quantity": [1, 1],
#         "unit_price": [100.0, 50.0],
#         "discount_percent": [150, 20],
#     })
# 
#     invalid = order_items[order_items["discount_percent"] > 100]
#     assert len(invalid) == 1
#     assert invalid.iloc[0]["item_id"] == 1
# 
# 
#     revenue = order_items["quantity"] * order_items["unit_price"] * (1 - order_items["discount_percent"] / 100)
#     assert revenue.iloc[0] < 0, "an unflagged discount_percent > 100 produces negative revenue"
#     print("PASS: test_discount_percent_over_100 (correctly detects invalid rows)")
# 
# 
# def test_quantity_zero():
#     """quantity == 0 is a valid-looking but meaningless line item: it contributes
#     zero revenue and shouldn't be counted as either a purchase or a return."""
#     order_items = pd.DataFrame({
#         "item_id": [1, 2, 3],
#         "order_id": [1, 1, 1],
#         "product_id": [1, 2, 3],
#         "quantity": [0, 5, -2],
#         "unit_price": [10.0, 10.0, 10.0],
#         "discount_percent": [0, 0, 0],
#     })
# 
#     revenue = order_items["quantity"] * order_items["unit_price"] * (1 - order_items["discount_percent"] / 100)
#     assert revenue.iloc[0] == 0, "zero quantity should contribute exactly zero revenue"
# 
#     zero_qty_rows = order_items[order_items["quantity"] == 0]
#     assert len(zero_qty_rows) == 1
#     print("PASS: test_quantity_zero")
# 
# 
# def test_future_order_date():
#     """An order_date in the future is a data-quality problem (clock skew, bad
#     manual entry, etc.). It should be detectable rather than silently included
#     in 'current' reporting periods."""
#     future_date = datetime.now() + timedelta(days=30)
#     orders = pd.DataFrame({
#         "order_id": [1, 2],
#         "customer_id": [1, 2],
#         "order_date": [datetime.now() - timedelta(days=1), future_date],
#     })
# 
#     future_orders = orders[orders["order_date"] > datetime.now()]
#     assert len(future_orders) == 1
#     assert future_orders.iloc[0]["order_id"] == 2
#     print("PASS: test_future_order_date")
# 
# 
# def run_all():
#     tests = [
#         test_order_item_with_missing_order,
#         test_discount_percent_over_100,
#         test_quantity_zero,
#         test_future_order_date,
#     ]
#     failures = 0
#     for t in tests:
#         try:
#             t()
#         except AssertionError as e:
#             failures += 1
#             print(f"FAIL: {t.__name__} -> {e}")
#     print(f"\n{len(tests) - failures}/{len(tests)} tests passed")
#     if failures:
#         raise SystemExit(1)
# 
# 
# if __name__ == "__main__":
#     run_all()